from tkinter import *
root=Tk()
root.geometry("655x333")
f1=Frame(root, bg="blue", borderwidth=6, relief=SUNKEN)
f1.pack(side=LEFT, fill=Y)
f2=Frame(root,bg="orange", borderwidth=8, relief= SUNKEN)
f2.pack(side=TOP, fill=X)
l=Label(f1,text="project tkinter_pycharm")
l.pack(pady=142)
l=Label(f2,text="Welcome to HAPPY DUSSERHA",font="Helvetica 16 bold", fg= "red", pady=20)
l.pack()
root.mainloop()